apiVersion: v2
name: weather-api
description: A Helm chart for Weather API Go application
type: application
version: 1.0.0
appVersion: "1.0.0"
EOF

cat > values.yaml << 'EOF'
replicaCount: 2

image:
  repository: weather-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  nodePort: 30002

ingress:
  enabled: true

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
