apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30004,"protocol":"TCP","serviceName":"musti-apps:live-go-portal","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["musti-apps/live-go-portal"]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"field.cattle.io/publicEndpoints":"[{\"port\":30004,\"protocol\":\"TCP\",\"serviceName\":\"musti-apps:live-go-portal\",\"allNodes\":true}]","field.cattle.io/targetWorkloadIds":"[\"musti-apps/live-go-portal\"]"},"name":"live-go-portal","namespace":"musti-apps"},"spec":{"ports":[{"name":"live-go-portal","nodePort":30004,"port":8080,"targetPort":8080}],"selector":{"app":"live-go-portal"},"type":"NodePort"}}
  creationTimestamp: "2026-02-23T13:57:49Z"
  name: live-go-portal
  namespace: musti-apps
  resourceVersion: "181833812"
  uid: 143919c8-e87e-4b25-8331-00d307bc31eb
spec:
  clusterIP: 10.43.90.93
  clusterIPs:
  - 10.43.90.93
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: live-go-portal
    nodePort: 30004
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-live-go-portal
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
