apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["musti-apps/real-currency-api"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2026-02-17T21:03:32Z"
  name: real-currency-api
  namespace: musti-apps
  resourceVersion: "179585102"
  uid: abee9e6f-ff46-40cb-bb0c-1fbbb52dfe96
spec:
  clusterIP: 10.43.130.84
  clusterIPs:
  - 10.43.130.84
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: musti-api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-real-currency-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
